### ISSUE TITLE
Custom server class for development

### ISSUE THREAD

**Issue by ylecuyer** [jgorset/facebook-messenger#113]
For development purpose I use the following server class:

```ruby
class ServerNoError < Facebook::Messenger::Server

  def call(env)
    begin
      super
    rescue Exception => e

        send("\xF0\x9F\x98\xB1")  #😱
        send(e.inspect)
        send(e.backtrace.join("\n")[0..636] + "...")

        @response.status = 200
        @response.finish

    end
  end

  private

  def send(text)
    
     sender_id = parsed_body["entry"][0]["messaging"][0]["sender"]["id"]

      Bot.deliver({
        recipient: {
          id: sender_id
        },
        message: {
          text: text
        }
      }, access_token: ENV['ACCESS_TOKEN'])
  end

end

run ServerNoError
```

Because when there is an error in the message handling, the messenger platform keep sending the message until the response code changes to 200.
Moreover, you have to read the log in order to find the corresponding stacktrace.

When there is a lot of 500 errors the messenger platform seems to stall the incoming messages.

![Preview](https://lh3.googleusercontent.com/uE7-vb8i2kw7aPBLcJgP61UoF42rHzVQJ_m5tnErmC8AZW6yTFNzXNnvvXnddnxDGWkLcbQbb-gGtxLwkMm1lXnZGOvK4dgyvzUmJ-7mFe2LfM3RJsHSObJCmVuGAz312OJezmIOTEREVJW-Yxy_ow8ny_79ZzHOxbVVqUTL-Bs5entTn1uDOy4neeSbXaH6ajvAjA3PRs_RNpZFNhBm0QRenhZL6QGfS7fANok-IGXd2yLky6iDLI1jNlCtVFQXniUn_GrcRygZdrxl45F2VUbWQ9vYYsumDK2yqCW9BuICaekSkO7ZKqXMWMPd1k9oE3BcYIh7fLMcS8uySvk3JWhAt9A6dNsL8vrb2S_-PxbcW6liAp-7zetFsof0squGRTVdiJLepWVXve7mk4nH2dVmnD-p3kIdcaaNcUsK5hzZt38fMUKz2uTg5qpb0RjyhP2hThjr9Gvtw6s2nIiBA_XyEvA6J1KMDwdQy45XT7wGkPFrhTQc2_2TyM5HFueEk4F1r1gmXLcXYk4yW_Q16Hj7jnnFpjqtQh1jiyxBi0jWU3ovTAALfshQStYsyjdhA-Zxwc-RYgIuCWQOV2GFTNiTYYV1JoBk5MpJS67LkyZ07YghtqYKtA=w1663-h935-no)

Maybe this can be integrated as an option?

**Comment by jgorset** [comment]
Sure, yeah! I'd be happy to merge that!
