### ISSUE TITLE
Any way to use message_echo?

### ISSUE THREAD

**Issue by abury** [jgorset/facebook-messenger#151]
Hey guys/gals

First off, thanks for the library. It's been a life saver. 😄 

I'm looking for a way of capturing all text sent from the page to a user (from the bot and humans) and the best way I can see that working is with the [message_echo webhook](https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-echo)

The readme states not to register for it, and there doesn't appear to be a separate block just for echos that I can see. Is there any other way to do this without DDosing the bot?

Thanks heaps

**Comment by jgorset** [comment]
Hey @abury! You're welcome!

That's a pretty good use case, actually. There's no way to use echoes without entering a vicious loop as it is, but it should be pretty easy to fix that and allow for the use case you're describing by looking at the `is_echo` attribute and directing it to a different block. I'd be very happy to merge a pull request that implements that!

**Comment by abury** [comment]
@jgorset I've opened PR #154 to address this.
