### ISSUE TITLE
routes.rb: uninitialized constant Facebook::Messenger::Server (Name Error)

### ISSUE THREAD

**Issue by nekapoor** [jgorset/facebook-messenger#156]
I'm getting this error in my Rails 4.1.5 app when I try to mount. I've followed the readme and not sure what the issue is. 

Any thoughts? 

Thanks so much!

**Comment by jgorset** [comment]
Hi @nekapoor,

I think we'll need to see your code and the stack trace to help you with that.

**Comment by jgorset** [comment]
I'm closing this pending a stack trace (but even so this issue may be better suited for StackOverflow).
