### ISSUE TITLE
Make environment variable names configurable

### ISSUE THREAD

**Issue by Fensterbank** [jgorset/facebook-messenger#157]
The environment variables used for the non-configuration-use of the gem are currently hardcoded in `environment.rb`.
It would be cool, if the environment variables can be configured or if there would be a way, to give the environment variable values manually, e.g. something like this (from another messenger gem)

    Messenger::Bot.config do |config|
      config.access_token = ENV['MESSENGER_ACCESS_TOKEN']
      config.validation_token = ENV['MESSENGER_VALIDATION_TOKEN']
      config.secret_token = ENV['MESSENGER_SECRET_TOKEN']
    end

In my use case I also have a telegram bot which has an access token too, so I would like to define specific environment variables.

PS: I think it would be possible with this ConfigurationProviders, but I have no clue how to use this and pass my own environment variables in it and there is no example of it.

**Comment by jgorset** [comment]
Hi @Fensterbank,

you're right that this is possible with configuration providers. All you have to do is create your own configuration provider that uses a different set of environment variables and configure the application to use that.

[`lib/facebook/messenger/configuration/providers/environment.rb`](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/configuration/providers/environment.rb) should be nearly exactly what you need – just change the names of the environment variables and you're good to go!
