### ISSUE TITLE
Setup for multiple pages

### ISSUE THREAD

**Issue by nicolrx** [jgorset/facebook-messenger#158]
I want to create a Messenger Bot used by different users for their Facebook pages. I created a rails app for this.

I successfully created the bot and it works when I do the set up for one page. Now, I follow the instructions to make my bot live on multiple Facebook Pages ("Make a configuration provider" section).

I'm new to rails and I'm not sure where to put the class ExampleProvider? I put it in my config/application.rb file:

    require_relative 'boot'
    
    require 'rails/all'
    
    # Require the gems listed in Gemfile, including any gems
    # you've limited to :test, :development, or :production.
    Bundler.require(*Rails.groups)
    
    module BotletterApp
      class Application < Rails::Application
        # Settings in config/environments/* take precedence over those specified here.
        # Application configuration should go into files in config/initializers
        # -- all .rb files in that directory are automatically loaded.
        config.paths.add File.join('app', 'bot'), glob: File.join('**', '*.rb')
        config.autoload_paths += Dir[Rails.root.join('app', 'bot', '*')]
      end
    
      class BotProvider < Facebook::Messenger::Configuration::Providers::Base
        def valid_verify_token?(verify_token)
          bot.exists?(verify_token: verify_token)
        end
    
        def app_secret_for()
          ENV['APP_SECRET']
        end
    
        def access_token_for(page_id)
          bot.find_by(user_id: page_id).page_access_token
        end
    
        private
    
        def bot
          MyApp::Bot
        end
      end
    
      Facebook::Messenger.configure do |config|
        config.provider = BotProvider.new
      end
    end

Then I have my app/bot/setup.rb file to create the bot. I don't know how to use the provider I created in place of the ENV variables?

    require "facebook/messenger"
    
    include Facebook::Messenger
    
    Facebook::Messenger::Subscriptions.subscribe(access_token: ENV["ACCESS_TOKEN"])
    
    Facebook::Messenger::Profile.set({
      get_started: {
        payload: 'GET_STARTED_PAYLOAD'
      }
    }, access_token: ENV['ACCESS_TOKEN'])

I searched in the Rails documentation how to make it work but unfortunately could not find anything.

**Comment by jgorset** [comment]
Hi @nicolrx,

I can see why this is confusing. The thing is that the configuration providers only work when you're receiving a message, because that's the only time the gem can infer which configuration you want. 

For example, if the message you received came from "Page A", it'll have its Facebook Page ID in it and the gem will pass that to `BotProvider#access_token_for` and use that to send a reply.

There's no way for the gem to know which page you want to subscribe to or which page's profile to set, but perhaps it would make more sense if you didn't need to pass it an access token and it's just do it for available pages. What do you think? Would that fit your use case?

**Comment by nicolrx** [comment]
Yes I think it would fit my use case. What I want to do is the following:
1) I have a rails app where users subscribe using the Facebook auth
2) They choose a page they administrate to setup their bot
3) They configure the bot (menu etc.)

Do you think that's possible.
What I don't understand is that, in theory people have to susbscribe the bot to one of their page no? When the bot sends message through a page, I need to have the Page access_token to do so, isn't it? (thus the : "access_token: ENV['ACCESS_TOKEN']"). How is it possible to send messages without access token?

Thank you for your help.

**Comment by jgorset** [comment]
That's possible, but not with the fix I prescribed above. 😁 That would just set the same profile for all the pages, which is not what you want. It seems to me that you actually need the granularity that is currently possible, but it means that you'll have to write some logic to juggle the access tokens and set the right profile for the right page.

> What I don't understand is that, in theory, people have to subscribe the bot to one of their page? 

Yes, you have to subscribe the bot to the page you want it to talk to, but just once (unless your bot goes offline, then you may have to do it again).

> When the bot sends message through a page, I need to have the Page access_token to do so, isn't it? (thus the : "access_token: ENV['ACCESS_TOKEN']"). How is it possible to send messages without access token?

If you're just responding to a message, you can use the convenience method `message.reply` and the gem will find the access token for you using your configuration provider. If you want to send a user a message out of the blue, though, you will have to find the right access token yourself (because the gem has no way of knowing which page that user belongs to).

**Comment by nicolrx** [comment]
Thanks. I updated my above answer to be more specific.

> It seems to me that you actually need the granularity that is currently possible, but it means that you'll have to write some logic to juggle the access tokens and set the right profile for the right page.

Could you be more specific? It's a HTTP request to set up the profile so maybe if I just do it once during the setup with the specific users inputs it would work?

**Comment by jgorset** [comment]
> Could you be more specific? It's a HTTP request to set up the profile so maybe if I just do it once during the setup with the specific users inputs it would work?

You'll need to use the _user's_ access token to get a _page_ access token from Facebook, and then store the page access token somehow so you can use it to send messages. Either way, you're right that you can just do this once when the user is setting up the bot, but you'll want to hang on to it in case you need to subscribe again later (following an outage, for example, as Facebook would unsubscribe you).

**Comment by nicolrx** [comment]
Got it, thank you so much. I will experiment and keep you updated!

**Comment by nicolrx** [comment]
Hi, I'm able to set up the bots for different pages. Unfortunately, the following line of my ConfigProvider is getting an error:

config/initializers/config_provider.rb
```
def bot
    Rails.application.class.parent::Bot
  end
```

I'm getting the following error:

> NameError (uninitialized constant BotletterApp::Bot):
>   
> config/initializers/config_provider.rb:17:in `bot'
> config/initializers/config_provider.rb:7:in `app_secret_for'

Do you know how should I name my app?

Thank you!

**Comment by nicolrx** [comment]
Hello, I found a way to setup the bot on different pages. Now I have a problem with my configuration provider. First I had to write MyApp::Application instead of Bot (no Bot class in my application file). The problem is I get the following error even if my db query works well in the Rails Console:


> ActiveRecord::StatementInvalid (SQLite3::SQLException: no such column: page_id.id: SELECT "core_bots".* FROM "core_bots" WHERE "page_id"."id" = ? LIMIT ?):


My config provider:
```
class ConfigProvider < Facebook::Messenger::Configuration::Providers::Base
  def valid_verify_token?(verify_token)
    ENV['VERIFY_TOKEN']
  end

  def app_secret_for(page_id)
    ENV['APP_SECRET']
  end

  def access_token_for(page_id)
    CoreBot.find_by_page_id(page_id).page_access_token
  end

  private

  def bot
    BotletterApp::Application
  end
end

Facebook::Messenger.configure do |config|
  config.provider = ConfigProvider.new
end
```

My application.rb file:
```
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module BotletterApp
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.paths.add File.join('app', 'listen'), glob: File.join('**', '*.rb')
    config.autoload_paths += Dir[Rails.root.join('app', 'listen', '*')]
  end
end
```

**Comment by jgorset** [comment]
It sounds like your implementation of `find_by_page_id` isn't right, @nicolrx – it's trying to look up a column called `page_id.id`, which doesn't seem right.

**Comment by nicolrx** [comment]
It seems like the access_token_for-method gets called with a hash, searching with something like {id: 1}. Where does that value is coming from? 
When I perform the "CoreBot.find_by_page_id(page_id).page_access_token" query in the Rails console, it works perfectly well.

**Comment by nicolrx** [comment]
I found the answer, it works: "CoreBot.find_by_page_id(page_id['id']).page_access_token"

**Comment by jgorset** [comment]
Oh, well spotted! That value is coming from [here](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/incoming/common.rb#L61), which is actually just the `recipient` bit of the object coming from Facebook (containing just `id`, as you've discovered).

That makes the README pretty confusing, though, and it's hard to blame you for thinking that `page_id` is, well, an id. I'd like to change it to be that way, actually, but considering that it would be a backwards-incompatible change I think the pragmatic thing to do here is to just change the README to reflect it.

**Comment by jgorset** [comment]
Thanks! ✨ :cake: :sparkles:

**Comment by nicolrx** [comment]
Thanks to you :)
