### ISSUE TITLE
Is the List template supported?

### ISSUE THREAD

**Issue by giolazzareschi** [jgorset/facebook-messenger#162]
I've beed trying to use this component

https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template

is it supported? While i'm trying to use it I keep receiving this message:

Facebook::Messenger::FacebookError ((#100) The URL provided is not whitelisted for messenger extensions):

**Comment by imthatcarlos** [comment]
@giolazzareschi I believe you're seeing that error as  result of trying setting `messenger_extensions: true` in one of the buttons on your list. You have to whitelist your domain: https://developers.facebook.com/docs/messenger-platform/messenger-profile/domain-whitelisting

**Comment by giolazzareschi** [comment]
@imthatcarlos hmmmmmmmmmmmmmm ok I missed that, thank you very much.

I'll close here thanks mate.
