### ISSUE TITLE
Not picking up Referral Messages -- am using Smooch would that impact it?

### ISSUE THREAD

**Issue by angelacode** [jgorset/facebook-messenger#166]
I am using Smooch for all the bot messages, but want to use facebook-messenger ruby gem to pick up when there is a referral on the m.me.

My set up:

```
# config.ru
require 'sinatra'
require 'facebook/messenger'

require_relative 'iron.io/smooch.rb'
require_relative 'bot.rb'

puts "run sinatra"
run Sinatra::Application

map("/webhook") do
  	puts "run messenger"
  	run Facebook::Messenger::Server
end
```

I have a class in the `bot.rb` file called `FbMessenger` which runs the following:

```
def run

    logger.progname = __method__

    #m = Message.new
binding.pry
    Facebook::Messenger::Subscriptions.subscribe(access_token: ENV["MESSENGER_ACCESS_TOKEN"])

    Bot.on :message do |message|

      json_log = {:message_id => message.id, :message_sender => message.sender, :message_text => message.text}
      logger.debug json_log

      FbMessenger.perform_async(message)

    end

    Bot.on :referral do |referral|

binding.pry
      referral.sender    # => { 'id' => '1008372609250235' }
      referral.recipient # => { 'id' => '2015573629214912' }
      referral.sent_at   # => 2016-04-22 21:30:36 +0200
      referral.ref       # => 'MYPARAM'
    end

  end
```
The only thing I can think of is that because smooch subscribes, messages don't come through?  What is the URI for the webhook that the messenger server listens for requests from Facebook Messenger?

**Comment by sorich87** [comment]
Did you subscription to postback events as well? For first time users, that's the event Facebook send instead of referral. https://developers.facebook.com/docs/messenger-platform/referral-params

**Comment by jgorset** [comment]
I'm closing this for lack of response.
