### ISSUE TITLE
The URL couldn't be validated. Response does not match challenge, expected value="1158435612", received="Error; wrong verify ..."

### ISSUE THREAD

**Issue by prdpspkt** [jgorset/facebook-messenger#168]
When I try to add webhooks in app page. This throws above error. But I have entered correct vefiy_token in both app and facebook webhook setup page. What might be the problem. 
`VERIFY_TOKEN: 'ramro-sathi-varification-code'`
![image](https://user-images.githubusercontent.com/8027379/29248878-da9bad6c-8042-11e7-9642-3aea63b05b92.png)

**Comment by jgorset** [comment]
That's right, @lbain! You can configure it to use something else (either a different environment variable or another source of configuration altogether), but the [default configuration provider](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/configuration/providers/environment.rb) looks to `VERIFY_TOKEN`, `APP_SECRET` and `APP_TOKEN`.

**Comment by sirasao2** [comment]
https://x-team.com/blog/how-to-get-started-with-facebook-messenger-bots/

This is great for help.

**Comment by ClauTrejo** [comment]
Hi, 
You can solve this problem checking Facebook credentials from app.js and web hook. Also, I made sure the workspace URL "url: 'https://gateway.watsonplatform.net/assistant/api'," it has to be the same as my workspace, it didn't say it in the manual 

Claudia Trejo

**Comment by tpriyanshu90** [comment]
Hi, I encountered a similar issue:
Here is the solution : firstly turnoff your server, type in your verify_token in the main file. Then restart the server. NOw type that verify token in the webhook. It's done.
cheers

**Comment by Mattw11486** [comment]
Can someone help with this? 
I too am getting this error I have done all of the suggestions in the forum and nothing helps 
![image](https://user-images.githubusercontent.com/76888925/166065466-c0b204ae-cc0d-4ead-9700-c04cc3bda224.png)
![image](https://user-images.githubusercontent.com/76888925/166065521-8e752303-6708-4382-bfb5-f458c99f3259.png)
