### ISSUE TITLE
Pass thread control?

### ISSUE THREAD

**Issue by f6v** [jgorset/facebook-messenger#173]
Hey, as far as I understand passing thread control isn't supported at the moment? https://developers.facebook.com/docs/messenger-platform/reference/handover-protocol/pass-thread-control

**Comment by jgorset** [comment]
That's right! Feel free to submit a pull request if you need it, though! 🎉

**Comment by echan00** [comment]
Interested in this feature as well. 

On another note, do you know whether it is possible to set the primary and secondary app receive roles programmatically?

**Comment by echan00** [comment]
FYI https://github.com/jgorset/facebook-messenger/pull/190

**Comment by echan00** [comment]
I'm working adding handover and take/pass thread control, will send a pull request once it's ready

**Comment by echan00** [comment]
I've made so many custom changes I think i'm better off just posting my repo here: https://github.com/echan00/facebook-messenger

**Comment by jgorset** [comment]
This made it into 1.3.0! :tada:
