### ISSUE TITLE
message.reply not working

### ISSUE THREAD

**Issue by JiProchazka** [jgorset/facebook-messenger#174]
Hi, I have problem with sending a reply:

```ruby
Bot.on :message do |message|
  message.reply(text: 'Hello, human!')
end
```

But direct sending is working:

```ruby
Bot.deliver({
    recipient: {
    id: '15242710xxxxxxxx'
  },
  message: {
    text: 'Human?'
  }
}, access_token: ENV['ACCESS_TOKEN'])
```

Any ideas?

Thanks

**Comment by jgorset** [comment]
That's odd. What happens? Do you get an error message?

**Comment by jgorset** [comment]
Huh! I'd like to take a closer look at this. Can you share your code by any chance?

**Comment by jgorset** [comment]
Thanks!

**Comment by JiProchazka** [comment]
Here is a simple Sinatra project.
Just fill in .env values and run `bundle install` and `ruby app.rb`.
[fb-test.zip](https://github.com/jgorset/facebook-messenger/files/1326318/fb-test.zip)

In the App.rb file there are two parts: `# working` and `#not working`. Comment it in/out and you will see.

Thanks

**Comment by JiProchazka** [comment]
Hi, did you manage to reproduce it?

**Comment by jgorset** [comment]
I'm sorry @JiProchazka, I've been a bad maintainer and completely forgot about this -- I hope you figured it out on your own, and otherwise I'm sorry for literally taking a year to get back to you. :grimacing:

**Comment by amrutjadhav** [comment]
Hey @JiProchazka, I am not expert of Sinatra application but I think there is something wrong with your mounted routes. Here is a sample project I found which is built on Sinatra. I think this might help you with the problem you faced.
https://github.com/kenzady/bot-sinatra
