### ISSUE TITLE
Always getting 400 errors

### ISSUE THREAD

**Issue by nocivus** [jgorset/facebook-messenger#175]
Hello, first of all thanks for the excellent gem.

I'm having trouble getting my bot to receive messages. I've tried both ngrok locally and deploying to heroku. I basically can get the verification working, and i do receive the post requests on rails. But then i don't get anything hitting the Bot.on :message part of the code.

On ngrok UI i see a 400 error whenever i get a post request, with the message "Error checking message integrity". Any ideas what that might be?

Thanks again!

**Comment by jgorset** [comment]
Thanks, and yep! Facebook signs all its requests with your secret key, so that you know it's coming from Facebook. Are you sure that you've configured your bot correctly?

**Comment by jgorset** [comment]
Thanks, and yep! Facebook signs all its requests with your secret key, so that you know it's coming from Facebook. Are you sure that you've configured your bot correctly?

**Comment by nocivus** [comment]
I changed to a different messenger gem and it worked with no core changes,
so i'm pretty sure there is something there that is not working for me :(

Pedro

**Comment by nocivus** [comment]
This one: https://github.com/netguru/messenger-ruby

Maybe they do something different, i don't know :(

Pedro

**Comment by jgorset** [comment]
Alright, well, glad you got that to work! :)
