### ISSUE TITLE
Ignoring read (no hook registered) Trigger callback mulitple times

### ISSUE THREAD

**Issue by Manidavid** [jgorset/facebook-messenger#189]
here is my code, it gives the below error which causes /bot called multiple times
```
message_content = if template
                          JSON.parse(template)
                        else
                          {
                            text: message,
                            quick_replies: quick_replies ? quick_replies : nil
                          }
                        end

      begin
        Bot.deliver(
          {
            recipient: {
              id: uid
            },
            message: message_content
          },
          access_token: ENV['ACCESS_TOKEN']
        )
      rescue => e
        Rails.logger.info '[debuz] Cannot deliver message to facebook: ' + e.message
      end
```

log:

[debuz] GET_STARTED_PAYLOAD {"id"=>"124495678232012"} postback
[debuz] sending 'Hello, Mani !' to user '1525496340849520'
[debuz] sending 'Greeting!! Pleased to meet you. How can I help today?' to user '1525496340849520'
Started POST "/bot" for 2a03:2880:2060:9fea:face:b00c:0:8000 at 2017-11-26 23:34:05 +0530
Ignoring read (no hook registered)
Started POST "/bot" for 2a03:2880:2060:8fe7:face:b00c:0:8000 at 2017-11-26 23:34:06 +0530
Ignoring read (no hook registered)
Started POST "/bot" for 2a03:2880:2011:5fe0:face:b00c:0:8000 at 2017-11-26 23:34:06 +0530
Ignoring read (no hook registered)

**Comment by cfurrow** [comment]
Hm, I wonder if the gem is returning a non-200 HTTP response code to Facebook. Facebook will try to resend webhooks to an app that had an error (e.g. did not return 200). 

Did you try to remove the `message_reads` subscription from your Facebook app? If you remove that, you should not receive those webhooks from facebook when a user reads your message.

**Comment by jgorset** [comment]
What @cfurrow said (:cake:)!
