### ISSUE TITLE
quick_replies: cannot retrieve message.attachments

### ISSUE THREAD

**Issue by gregcha** [jgorset/facebook-messenger#194]
Hello, 

For some reason, I cannot retrieve attachments from a quick_reply (I ask for a location).
I'm sending the following so the user can share his location:
```
Bot.deliver({
      recipient: {
        id: sender_id
      },
      message: {
        text: TEXT[:ask_location],
        quick_replies: [
          {
            content_type: 'location',
          }
        ]
      },
    }, access_token: ENV['ACCESS_TOKEN'])
```

Following Facebook documentation, the answer should look like this: 
```
{
  "object": "page",
  "entry": [
    {
      "id": "<PAGE_ID>",
      "time": 1472672934319,
      "messaging": [
        {
          "sender": {
            "id": "<PSID>"
          },
          "recipient": {
            "id": "<PAGE_ID>"
          },
          "timestamp": 1472672934259,
          "message": {
            "mid": "mid.1472672934017:db566db5104b5b5c08",
            "seq": 297,
            "attachments": [
              {
                "title": "Facebook HQ",
                "url": "https://www.facebook.com/l.php?u=https%....5-7Ocxrmg",
                "type": "location",
                "payload": {
                  "coordinates": {
                    "lat": 37.483872693672,
                    "long": -122.14900441942
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```
I receive the answer but for some reason I don't have anything related to the attachments array. 
It worked fine few months ago. Did something change recently regarding this gem or the facebook messenger API? 

Thanks a lot for your help !

**Comment by jgorset** [comment]
That's odd. Do you get an array of attachments for other things, or is it just this in particular where it doesn't work?

**Comment by jgorset** [comment]
It really [should work](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/incoming/message.rb#L55), anyway.
