### ISSUE TITLE
How to deal with user that do not have Facebook account but only Messenger account???

### ISSUE THREAD

**Issue by Guillaumejfrt** [jgorset/facebook-messenger#202]
Hi,

I am trying to manage the case when a user do not have Facebook account but only Messenger account.

Is the gem able to detect this distinction and how can I handle it? 
Is there a way to grab user information such as profile picture, first_name, last_name, etc....

Indeed, the classical API Graph request to get User Profile information does not wordk:
```
curl -X GET "https://graph.facebook.com/v2.6/<PSID>?fields=first_name,last_name,profile_pic&access_token=<PAGE_ACCESS_TOKEN>"
``` 

It answers with:

```
{
  "error": {
  "message": "(#100) No profile available for this user.",
  "type": "OAuthException",
  "code": 100,
  "error_subcode": 2018218,
  "fbtrace_id": "G2oz2QE++k1"
  }
}
```

thanks for your help
Guillaume

**Comment by jgorset** [comment]
Hi @Guillaumejfrt! I haven't run into this before, but judging from [the documentation](https://developers.facebook.com/docs/messenger-platform/identity/user-profile) it looks like you're out of luck.
