### ISSUE TITLE
Why passing URL value to data-ref doesn't work

### ISSUE THREAD

**Issue by aldrienht** [jgorset/facebook-messenger#203]
In **Send to Facebook**, I wanna pass URL value to data-ref and to be fetch using
**optin.ref** , BUT doesn't worked.
Simple string works......

`
-div class="fb-send-to-messenger" 
  messenger_app_id="APP_ID" 
  page_id="PAGE_ID" 
  data-ref="http://sadas...." 
  color="blue " 
  size="standard">

`

**Comment by sorich87** [comment]
You can encode it then decode when reading.

**Comment by aldrienht** [comment]
Hi @sorich87 , I tried to used **CGI.escape(url)** and output is:
`"http%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F2552%2F0076%2Fproducts%2Fni313171_600_thum1_10_674_17041_large.jpg%3Fv%3D1510724864"`

And plan to **CGI.unescape(optin.ref)** in **/bot/listen.rb**.

But, my **send-to-messenger** button in my view does not show up thus I can't continue the process.
Returning the value of `data-ref="simple text"` has no problem.

**Comment by aldrienht** [comment]
I tried to dissect the url, I found out the error comes in special characters like (? | % ....)
Even I encode it like **CGI.escape('?')** => "**%3F**", encoded value contains unacceptable character/s for **data-ref.**
