### ISSUE TITLE
Changes we are making to the Facebook Platform.

### ISSUE THREAD

**Issue by DSKonstantin** [jgorset/facebook-messenger#205]
`'raise_errors': (#200) Access to this data is temporarily disabled for non-active accounts due to changes we are making to the Facebook Platform (Facebook::Messenger::Subscriptions::Error)`

Anyone know the details of this problem?

Is this related to this problem? - https://www.theguardian.com/technology/2018/mar/21/mark-zuckerberg-response-facebook-cambridge-analytica

Thanks, all.

**Comment by mjnguyennz** [comment]
i don't know the details, but I got my chatbot to work again by replacing the line in my code: 
`Facebook::Messenger::Subscriptions.subscribe(access_token: ENV["ACCESS_TOKEN"])`
with 
`HTTParty.post 'https://graph.facebook.com/v2.9/me/subscribed_apps', query: {
          access_token: ENV["ACCESS_TOKEN"]
        }
`
the subscribe method in the gem tries to hit the v2.6 version of facebook api, which responds with that error. but it doesn't seem to error for me when I use v2.9. YMMV

**Comment by DSKonstantin** [comment]
@mjnguyennz Thank you for the fast updates. 👍

**Comment by nicolrx** [comment]
Unfortunately @mjnguyennz, It's not working for me. Maybe an update from Facebook?

**Comment by k-p-jones** [comment]
I've been having the same issue all weekend.

Might be something to do with this ->

https://developers.facebook.com/status/issues/205942813488872/

**Comment by amrutjadhav** [comment]
This is not a API issue. It's because, facebook changing policies so that app (Mostly in testing/development) should not get extra access to people data.

**Comment by tsabbay** [comment]
yes, we are facing the same issue:
https://graph.facebook.com/v2.7/' + pageID + '/subscribed_apps


we tested few diff api versions as well..
error:
Access to this data is temporarily disabled for non-active accounts due to changes we are making to the Facebook Platform

**Comment by YusufBesim** [comment]
Same here our webhooks down

**Comment by jimgreer** [comment]
As a temporary workaround I was able to just remove the subscription request. Per the ruby client docs, this subscription is not required every time your app runs or restarts, though FB may require it again if your app is unresponsive.

**Comment by nicolrx** [comment]
Last update, not giving any ETA... https://developers.facebook.com/blog/post/2018/03/26/facebook-platform-changes/

**Comment by nicolrx** [comment]
My users can't log in today. Am I the only one with this issue? I get the following statement:

Platform Access Disabled: Access temporarily disabled due to changes to the Facebook Platform

**Comment by jgorset** [comment]
I'm updating the gem to use API version 2.9, so closing this!
