### ISSUE TITLE
Documentation for Testing

### ISSUE THREAD

**Issue by peterwdj** [jgorset/facebook-messenger#215]
I've been wrangling with getting tests to work all afternoon, and have finally got there! So I thought I would write some documentation on how to mimic an event being registered and the behaviour when that occurs. 

I've written it up on a new branch, but have been unable to push this to GitHub as I don't have the correct permissions. Would it be possible for someone to allow me to push a branch submit a PR please? :innocent: Thank you!

**Comment by amrutjadhav** [comment]
I think nobody has permission to push to repo directly. But you can fork this repo and push your changes to your fork. Then you can create PR to this repo from your fork. :)

**Comment by peterwdj** [comment]
Ahhh my bad, thanks so much @amrutjadhav - will do so this evening!

**Comment by amrutjadhav** [comment]
@peterwdj thank you for written documentation for test. Currently I am also writting tests had some difficulty understanding the flow. Your documentation may help me to understand it better. :)

**Comment by peterwdj** [comment]
@amrutjadhav I hope so!

**Comment by peterwdj** [comment]
@amrutjadhav I've submitted a PR now, so at the very least you can see the documentation I've written even if it is not yet merged into master :-) 

https://github.com/jgorset/facebook-messenger/pull/216

**Comment by jgorset** [comment]
Merged!
