### ISSUE TITLE
Returning early 

### ISSUE THREAD

**Issue by abury** [jgorset/facebook-messenger#217]
Hey team

So, I feel like this is a stupid question, but how do you return early from within a block in the bot? When we use return we get the following exception:

```ruby
LocalJumpError · unexpected return
```

I feel like this is happening because of a misunderstanding I have of basic ruby. Should we be using `exit` or `break` instead?

Thanks,
Aron

**Comment by jgorset** [comment]
Hi @abury! Yeah, `break` sounds about right. This is relevant to your interests: https://makandracards.com/makandra/46939-ruby-a-small-summary-of-what-return-break-and-next-means-for-blocks

**Comment by abury** [comment]
Hey @jgorset 

I tried break but was still getting a local jump error: `unexpected break`

`next` seems to do the trick 👍
