### ISSUE TITLE
#<Facebook::Messenger::FacebookError: (#546) The type of file you're trying to attach isn't allowed. Please try again with a different format

### ISSUE THREAD

**Issue by adeprem** [jgorset/facebook-messenger#221]
Hi, 
I'm getting this error when I try to upload a video attachment instead of an audio one. Any idea why? 

> #<Facebook::Messenger::FacebookError: (#546) The type of file you're trying to attach isn't allowed. Please try again with a different format

For info, what's in my code is: 
> message.reply(
          attachment: {
            type: 'audio',
            payload: {
              url: 'https://clyp.it/42khxiae.mp3'
            }
          }
        )

I also tried it to do it this way (with the file in a folder) and it was unsuccessful as well 
<img width="471" alt="capture d ecran 2018-07-29 a 16 04 25" src="https://user-images.githubusercontent.com/31307153/43367167-483c631a-9349-11e8-943a-2d78b471398b.png">

**Comment by amrutjadhav** [comment]
@adeprem The file URL i.e. https://clyp.it/42khxiae.mp3 is not a actual mp3 file URL. When you access this URL is redirecting to https://clyp.it/announcement/direct-file-access a HTML page which is not allowed as attachment by the API. So give URL of actual file not the redirecting route. I tested with the actual file URL and it works.
