### ISSUE TITLE
Needs Active Access Token / No Enough Permissions 

### ISSUE THREAD

**Issue by ejohnst2** [jgorset/facebook-messenger#226]
`/Users/elijohnston/.rvm/gems/ruby-2.5.1/gems/facebook-messenger-1.1.1/lib/facebook/messenger/subscriptions.rb:73:in 'raise_errors': (#100) No enough permission to subscribe one or more of fields you specified (Facebook::Messenger::Subscriptions::Error)`

Every time I try to run my rails server, or any rails command for that matter it will either yield this error or an error about an active access token. I've even tested hardcoding the token in to see if it was an issue reading env variables but was still yielding permissions error. 

When I comment out my bot code in `app/bot/listen.rb` then I can launch the rails server, but then once I try to post to bot on Messenger, I get the same message in my terminal. 

```
Started GET "/bot?hub.mode=subscribe&hub.challenge=1798107466&hub.verify_token=anythingiwant" for 2a03:2880:11ff:d::face:b00c at 2018-09-23 09:05:23 +0800
Cannot render console from 2a03:2880:11ff:d::face:b00c! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Started POST "/bot" for 2a03:2880:40ff:3::face:b00c at 2018-09-23 09:10:12 +0800
Cannot render console from 2a03:2880:40ff:3::face:b00c! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Facebook::Messenger::Subscriptions::Error ((#100) No enough permission to subscribe one or more of fields you specified):

app/bot/listen.rb:4:in `<main>'
config/initializers/facebook_messenger.rb:5:in `block (2 levels) in <main>'
config/initializers/facebook_messenger.rb:5:in `each'
config/initializers/facebook_messenger.rb:5:in `block in <main>'
config/initializers/facebook_messenger.rb:9:in `block in <main>'
Started POST "/bot" for 2a03:2880:40ff::face:b00c at 2018-09-23 09:10:26 +0800
Cannot render console from 2a03:2880:40ff::face:b00c! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Ignoring message (no hook registered)

```
This problem began a month ago, but before that was not giving any issues. Any help would be appreciated! Been working on this with @juliettech13.

**Comment by amrutjadhav** [comment]
@ejohnst2 `Needs Active Access Token` could be caused due to the expiration of the access token. I think you are using `short-lived access token`. This is the default token Facebook provide when you demand one. This access token has expiration time set to it which is very short eg. 1-2 hour. So I would suggest, you get `long-lived access token`.
https://developers.facebook.com/docs/facebook-login/access-tokens/#usertokens

**Comment by jgorset** [comment]
This seems resolved, so I'm closing it!
