### ISSUE TITLE
Postback Button Action Unsuccessful

### ISSUE THREAD

**Issue by azizulhakim-f** [jgorset/facebook-messenger#228]
Hello, 
My chatbot was running perfectly. But recently from 2-3 weeks, whenever few generic template card's postback button is pressed, this message is shown:

> Action Unsuccessful.
> There was an error while delivering your message to the bot. Please try again later.

This problem is only on some specific buttons. But these buttons was working previously. And now, no response is being sent to server either, when these buttons are pressed. I'm desperate about this problem, please help me fix this problem. 
![image](https://user-images.githubusercontent.com/20112349/46622952-efbf1d80-cb4d-11e8-9c0f-99aef3169bbb.png)

**Comment by amrutjadhav** [comment]
@azizulhakim-f I think, this problem is on the Facebook side because as per error message, Facebook is having the problem delivering messages to your webhook. Just for confirmation, check your settings of the app in developer panel.

**Comment by jgorset** [comment]
This seems resolved, so I'm closing it!
