### ISSUE TITLE
Can i passing all users?

### ISSUE THREAD

**Issue by tretjakan** [jgorset/facebook-messenger#230]
Hi there! As I see in the documentation about handover protocol we can Pass Thread Control in one request only for one User. Can I pass to the page inbox all users?

**Comment by amrutjadhav** [comment]
As per documentation, I don't think facebook allows to pass control to page inbox to all users. Every `pass_thread_control` event is associated with a single recipient Id. And also FB API expects `recipient.id` to be `Integer` not array. 
You can check request thread control API reference here
https://developers.facebook.com/docs/messenger-platform/reference/handover-protocol/request-thread-control
