### ISSUE TITLE
How do I listen to events?

### ISSUE THREAD

**Issue by nekapoor** [jgorset/facebook-messenger#236]
I'm pretty confused. I'm using Rails and I've mounted the bot in my routes.rb file. 

But I don't really understand how I set everything up to receive callbacks? For example, I want to receive referral callbacks. 

How do I do that? I've got this Listener class in app/bot but how does that even get called? 

Any thoughts/insight would be great. Thanks so much.

**Comment by cfurrow** [comment]
From the README: https://github.com/jgorset/facebook-messenger#usage

```ruby
# bot.rb
require 'facebook/messenger'

include Facebook::Messenger

Bot.on :message do |message|
  message.id          # => 'mid.1457764197618:41d102a3e1ae206a38'
  message.sender      # => { 'id' => '1008372609250235' }
  message.seq         # => 73
  message.sent_at     # => 2016-04-22 21:30:36 +0200
  message.text        # => 'Hello, bot!'
  message.attachments # => [ { 'type' => 'image', 'payload' => { 'url' => 'https://www.example.com/1.jpg' } } ]

  message.reply(text: 'Hello, human!')
end
```

You would put the above code in some file, perhaps in `lib/facebook_messenger_listener.rb` and make sure that your Rails application loads that file. You would do that by calling `require 'facebook_messenger_listener'`, probably in your application.rb file.

And you've also mounted this facebook_messenger engine in your routes file:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  # ...
  mount Facebook::Messenger::Server, at: 'bot'
end
```

With those two things setup, it will all work together. The requests coming into `/bot` (according to your routes.rb file) will get passed along to your listener code, `lib/facebook_messenger_listener.rb`.

That's it.

**Comment by carlosfernandes** [comment]
Events like feed webhook are redirect to the Bot.on :postback listener to? I'm a little confused about how to use the gem for page webhooks.

Thanks.

**Comment by cfurrow** [comment]
No, the `feed` webhook is NOT handled by this gem at all. This gem handles Facebook Messenger webhooks only. You can see the webhooks that this gem *can* handle by looking here: https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/incoming.rb#L23-L35

```ruby
      #
      # @return [Hash] Hash containing facebook messenger events and its event
      #   handler classes.
      EVENTS = {
        'message' => Message,
        'delivery' => Delivery,
        'postback' => Postback,
        'optin' => Optin,
        'read' => Read,
        'account_linking' => AccountLinking,
        'referral' => Referral,
        'message_echo' => MessageEcho,
        'message_request' => MessageRequest,
        'payment' => Payment,
        'policy_enforcement' => PolicyEnforcement
      }.freeze
```

**Comment by carlosfernandes** [comment]
So the only way to handle this two webhooks is not using this gem or there is another way to inject a function to the bot callback for hadle the feed webhook?

**Comment by cfurrow** [comment]
@carlosfernandes I suppose you could fork this gem and add the code that may be able to handle that webhook. You can look at the other webhooks in this repository to see how you'd do that (creating the right `Incoming` class, etc). Or, perhaps there is another gem out there you could use.

This gem is only for facebook messenger, not *all* facebook page stuff. So it's not a relevant thing to add to it presently. But you can do whatever you want to a forked version of the gem, but you'd have to maintain that yourself, obviously.
