### ISSUE TITLE
Should i implement background responder for my chatbot? 

### ISSUE THREAD

**Issue by YanCarlos** [jgorset/facebook-messenger#237]
Hi, excuse me for this question but i'm starting to know this gem and i have a doubt, is neccessary to implement something like Sidekiq for my bot? i mean, if i a don't use it, my users will have problems with answers?

**Comment by amrutjadhav** [comment]
@YanCarlos  No, you don't need to use Sidekiq for responding to users. You can do that in a standard synchronous way. And also you should not process requests in an asynchronous way as Facebook has a response time limit of 20 sec. Sidekiq is for background job processing. If you have a requirement where you have to generate reports or job which you want to perform is going to take much more time then, you could use Sidekiq. Try to make as much as less processing when you get an event from Facebook. So your response time is less. This will help your app to handle more request.

**Comment by jgorset** [comment]
What @amrutjadhav is exactly right. :blush:
