### ISSUE TITLE
Error when i tried to subscribe my bot

### ISSUE THREAD

**Issue by YanCarlos** [jgorset/facebook-messenger#238]
I'm getting this error, do you know why is it happening? 
<img width="1023" alt="Screen Shot 2019-03-11 at 1 32 04 AM" src="https://user-images.githubusercontent.com/5903138/54104397-b65d3900-439d-11e9-8776-77338c07dbb7.png">

Note: my facebook app is still in development

**Comment by amrutjadhav** [comment]
@YanCarlos As per I see, you are trying to subscribe to `feed, mention, name` but your facebook app doesn't have `manage_pages` permission. So first apply for permission from facebook dashboard then you can try again. And for information, while you are developing, keep your Facebook app in `development` mode. Apps in `development` mode, don't require any permissions but they can only be accessed by authorized users. 

And for security, avoid displaying your `access_token`.

**Comment by YanCarlos** [comment]
@amrutjadhav thanks!
