### ISSUE TITLE
Upgrade to v2.10 or further.

### ISSUE THREAD

**Issue by mijoharas** [jgorset/facebook-messenger#239]
Not needed for a while, but 2.9 is EOL on July 22nd (https://developers.facebook.com/tools/api_versioning). Upgrading from 2.9 to 2.10 will have a small behaviour change if we don't integrate app_secret_proof so we should probably do that too (https://developers.facebook.com/docs/graph-api/securing-requests/).

If we're moving to 2.10 there are no changes further required to move all the way to 3.2 so I'd suggest doing that too.

Sorry, I don't have a Pr at the moment due to a facebook bug affecting dev apps, but will probably raise one once it's fixed.

**Comment by egor-moysevich** [comment]
@mijoharas , could you please share what is the issue which affects dev apps?
Asking cause i've noticed app in dev mode can't reply to users' messages constantly saying:
"This person isn't available right now. (subcode: 1545041)"

**Comment by pascoemitch** [comment]
@egor-moysevich This is the current issue being tracked on [Facebook's Bug Tracker](https://developers.facebook.com/support/bugs/316004652414423/?disable_redirect=0)

**Comment by mijoharas** [comment]
@egor-moysevich yeah, it's that one.
https://developers.facebook.com/support/bugs/316004652414423/?disable_redirect=0

**Comment by pascoemitch** [comment]
@mijoharas are you planning on opening a PR for this sometime soon?

**Comment by mijoharas** [comment]
Sorry, had a few days off and didn't get to this. Yeah, I'll create a Pr for this quickly (will probably have one by tomorrow at the latest.)

**Comment by mijoharas** [comment]
Pr ready. Let me know your thoughts.
