### ISSUE TITLE
How to update graph api

### ISSUE THREAD

**Issue by vbilta** [jgorset/facebook-messenger#240]
How to update facebook graph api or extend with new version

**Comment by jgorset** [comment]
Hi @vbilta. The Facebook Graph API version is coded into the gem, so you can't switch between versions. The current version of the gem (1.2.0) [uses Graph API version 3.2](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/bot.rb#L16), but if you want to use an older version you may be able to find it by downgrading the gem.
