### ISSUE TITLE
Support for 'messaging_game_plays' webhook.

### ISSUE THREAD

**Issue by egor-moysevich** [jgorset/facebook-messenger#242]
Hello! 

Is it planned to extend the list of webhooks this gem supports with 'messaging_game_plays'?
Docs: https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_game_plays/

In general, it's about playing around the instant games but in terms of Messenger's bot its just the single webhook missing.

**Comment by egor-moysevich** [comment]
@jgorset , do you have any chance to think about it? Thanks in advance.

**Comment by jgorset** [comment]
Hi @egor-moysevich! That's kinda cool. I'm not planning to do it, because I don't need it, but I'd be happy to merge it if you do. :blush:

**Comment by egor-moysevich** [comment]
hey, @jgorset !
Created PR for this: https://github.com/jgorset/facebook-messenger/pull/243

**Comment by jgorset** [comment]
Nice!
