### ISSUE TITLE
Best way to capture the subdomain request?

### ISSUE THREAD

**Issue by ryanwaits** [jgorset/facebook-messenger#246]
Hey guys - seriously great job here, been using for a few years now and has made my life much easier, so thank you! 

I'm currently working on migrating my current Rails bot into multi-tenancy, but am having a bit of trouble wrapping my head around how to best implement that. I have a Rails API integration that I can either call out to via an Active Resource call or I can connect to my db with ActiveRecord - however I need to know where the requestor is coming from in order to know which client I am serving.

Any thoughts on a good solution here? My first thoughts were to access the subdomain on every request - but haven't been able to figure out how to best do that yet. 

Appreciate the help!

**Comment by jgorset** [comment]
Hi @ryanwaits! Happy to hear that it's been helpful to you. :blush: 

I'm not sure I understand what you want to accomplish, though. Can you explain it like I'm 5?

**Comment by jgorset** [comment]
I take it you found a way to fix this, so I'll close it. :slightly_smiling_face:
