### ISSUE TITLE
Multiple clients to a Single Bot without including Facebook::Messenger into App namespace

### ISSUE THREAD

**Issue by wflanagan** [jgorset/facebook-messenger#249]
First, let me say that I'm disappointed to open a ticket for essentially tech support. But, 4+days and open "developer/freelancer" requests on 2 services didn't find anyone that would be willing to give me guidance. I'll definitely try to issue a doco pull request when this is over.  

Let me try to explain my situation. 

We have an existing bot service. We are attempting to add the ability to use Facebook Messenger as an additional channel.  Our users build and maintain 1 or more Bots.  These bots are envisioned to be able to connect to 1 Facebook page each (for now).  

We've configured a single messenger & webhook enabled application in Facebook's Developer console for our application.  We've configured the callback URL, webhooks, etc. in Facebook and have verified that we're getting POSTs and GETs from Facebook.

When one of our users wants to add one of their configured Bots to a Facebook page, they authenticate as a user (using OAuth so we have a user_access_token), then they select the page from a list of their mangaed pages. We store this information, including a page access token that's used by our bot.  That information is stored in a model called a "Client." (you'll see it in the logs for the attached gist).  

So, problem 1.  When we create a new client, we issue the command as an after_create action:
`::Facebook::Messenger::Subscriptions.subscribe(access_token: settings['facebook_page_access_token'])`
the returns an error about a subcode. How do we make that part work?  It's not clear from the docs what i'm doing wrong there.  That should be issued 1 time. We do it right after we store the page_access_token, but it doesn't work. 

To get past that, for now, we are manually attaching the page to the Facebook App bot. Then, we're configuring the page itself for the Bot to be the main handler of a message.  This works, we see the POST for multiple pages on the callback_url in our app.  

Problem 2.  But, 100% of the time, we get
`Ignoring message (no hook registered)`
and it returns 200.  Assuming that this is not the subscription problem above, and that we need a configuration provider, we added this as an initializer.  This is included in the gist linked.  I added puts statements, and we see the page_app_secret called 2 times per each post. But, we don't see any other methods called.  

I'm at a loss now about what the next step is. I feel VERY close to this working.  But, i can't seem to make the Bot.on :message logic ever be called. 

As I said, here's a gist with my ENTIRE configuration in it.  Any thoughts on what i'm doing wrong?  

https://gist.github.com/wflanagan/302671477601cd2adc872afe2c5385e4

Your thoughts and help would be most appreciated.

**Comment by jgorset** [comment]
Hi @wflanagan! Please don't worry about having to ask for tech support (especially when you looked around and documented it so thoroughly first). I'll do my best to help. :slightly_smiling_face: 

This is a weird issue, though. I haven't seen problem no. 1 before, but I can tell that it's an error from Facebook that this gem is just [passing through](https://github.com/jgorset/facebook-messenger/blob/master/lib/facebook/messenger/subscriptions.rb#L75). To rule this gem out as an error source, consider crafting and sending the same [subscription request](https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/) using another tool (like Facebook's Graph API explorer, or cURL). If that still doesn't work, and you're sure that the access token you're giving it should work, then I think your best bet is to pursue it on [Facebook's bug tracker](https://developers.facebook.com/support/bugs/).

As for problem no. 2, it could be that your code to register the hooks are not run. I'm guessing that's Ruby on Rails, and I'm not sure it'll load the code in your controllers before they're hit by a request. Can you try requiring it explicitly and seeing if that works?

**Comment by jgorset** [comment]
I guess you were able to solve this. 🙂
