### ISSUE TITLE
Current version of gem still seems to call v2.9

### ISSUE THREAD

**Issue by abury** [jgorset/facebook-messenger#252]
Hey all

We've just upgraded the gem to the latest version (1.4.0) and updated our tests to stub `https://graph.facebook.com/v3.2/me/`, but it kept failing, saying that it was still trying to call `https://graph.facebook.com/v2.9/me/`

I ensured I was using the right version and looked into the gem, it looks like 2.9 is still being referenced in `profile.rb`

```ruby
 module Profile
      include HTTParty

      # Define base_uri for HTTParty.
      base_uri 'https://graph.facebook.com/v2.9/me'
```

Was this missed or left on purpose? With v2.9 being deprecated in 9 days, we should get an update out asap for this one.

I'll do some testing and get a PR ready if upgrading to 3.2 is trivial and doesn't contain any breaking changes.

**Comment by abury** [comment]
Created https://github.com/jgorset/facebook-messenger/pull/253 to upgrade profiles version

**Comment by abury** [comment]
@jgorset any update on this one?

**Comment by jgorset** [comment]
Sorry for being so slow on this one, @abury! I had a long holiday and got married and stuff. Thanks for contributing this. I'll merge and release a new version straight away.

**Comment by jgorset** [comment]
v1.4.1 is on Rubygems now!

**Comment by abury** [comment]
Congratulations @jgorset! Hope the wedding went well! 💍

**Comment by jgorset** [comment]
Thanks @abury! :D
