### ISSUE TITLE
Error checking message integrity

### ISSUE THREAD

**Issue by rafayet-monon** [jgorset/facebook-messenger#258]
In the `check_integrity` method the line 

```
         raise BadRequestError, 'Error checking message integrity'.freeze \
           unless valid_signature?
```

always raises the exception. I don't understand why but Is this because facebook changed something??

Or does the `generate_hmac(content)` method needs some change?

**Comment by jgorset** [comment]
Hi @rafayet-monon! Are you still having this issue? Since nobody else seems to be having it, I suspect it might be that you're missing some configuration or might have gotten your secret key from Facebook wrong. Feel free to reopen this issue if not and I'll try to help out.
