### ISSUE TITLE
global "include Facebook::Messenger" bad style and possibly dangerous?

### ISSUE THREAD

**Issue by phoeinx** [jgorset/facebook-messenger#264]
As shown in the READ.ME Facebook::Messenger gets included at top level, which according to RuboCop is bad style, because it affects the behaviour of Object. (Refer: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MixinUsage) 

```
# app/bot/example.rb
include Facebook::Messenger

Bot.on :message do |message|
  message.reply(text: 'Hello, human!')
end
```

This altered code snippet works, too:

```
# app/bot/example.rb

Facebook::Messenger::Bot.on :message do |message|
  message.reply(text: 'Hello, human!')
end

```

We wanted to ask if there is another reason for including Facebook::Messenger than namespaces -> being able to use Bot instead of Facebook::Messenger::Bot. If there is no other reason we would recommend changing the documentation to the second version without the include for the above mentioned reasons.

**Comment by jgorset** [comment]
Good point! Thanks. Fixed in 64fe1f5
