### ISSUE TITLE
Not support event feed ?

### ISSUE THREAD

**Issue by nguyendinhlam88** [jgorset/facebook-messenger#283]

**Comment by cvquez** [comment]
Creado el pull request para [Feed](https://github.com/jgorset/facebook-messenger/pull/286)

**Comment by y0608** [comment]
@cvquez good job on the PR.
Lets hope @jgorset sees and merges it.

**Comment by 645383** [comment]
any updates? is the project maintained? Readme looks outdated - https://github.com/jgorset/facebook-messenger/blob/master/README.md?plain=1#L458, `access_token_for` should accept `page_id`

**Comment by y0608** [comment]
@645383, I do not think it is maintained :(
I wrote an email to @jgorset, but he isn't answering.

**Comment by jgorset** [comment]
Hi @645383 and @y0608! I'm not using this personally anymore, and I unfortunately only saw the e-mail and pull request now, but I'm happy to merge it. Thanks for doing it and keeping the library up to date!

**Comment by jgorset** [comment]
Closing this as the pull request is merged :)

**Comment by romiras** [comment]
Could you please release a tag?
